name: "🧹 Chore / Test"
description: Maintenance, CI, dependencies, or tests
title: "[Chore] "
assignees:
    - DanielButler1
body:
    - type: dropdown
      id: area
      attributes:
          label: Area
          options:
              - API
              - Data
              - Docs
              - Other
              - SDKs
              - Web
      validations:
          required: true
    - type: textarea
      id: scope
      attributes:
          label: Scope
          placeholder: What needs doing and why.
      validations:
          required: true
